### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [480, 512] at entry 0 and [0, 512] at entry 1

### ISSUE THREAD

**Issue by wnqw** [foocker/lsp#30]
---------- Generator networks initialized -------------
-------------------------------------------------------
initialize network with normal
/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/functional.py:581: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:639.)
  normalized, onesided, return_complex)
  0%|                                                                                                                  | 0/251 [00:00<?, ?it/s]Training epoch 0
  0%|                                                                                                                   | 0/35 [00:00<?, ?it/s]
  0%|                                                                                                                  | 0/251 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    main(cfg)
  File "train.py", line 15, in main
    trainer.fit()
  File "/media/yulun/12THD1/Wenqing_Projects/lsp/lib/solover/trainer.py", line 314, in fit
    for step, batch in enumerate(tqdm(self.train_dataloader)):
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/wenqingwang/anaconda3/envs/lsp2/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [480, 512] at entry 0 and [0, 512] at entry 1

**Comment by wnqw** [comment]
I processed the data as instructed and have the correct files in the 'data' folder, but when I tried to run 'Audio2Feature' task with 'audio' test block, it gives this error message. Could you please take a look, I would really appreciate it!

**Comment by foocker** [comment]
> I processed the data as instructed and have the correct files in the 'data' folder, but when I tried to run 'Audio2Feature' task with 'audio' test block, it gives this error message. Could you please take a look, I would really appreciate it!

see readme.
