### ISSUE TITLE
get train data

### ISSUE THREAD

**Issue by heiheiwangergou** [foocker/lsp#9]
when i bash run.sh 
get this error
Traceback (most recent call last):
  File "demos/lsp_data_generator.py", line 599, in <module>
    main(args)
  File "demos/lsp_data_generator.py", line 394, in main
    deca = DECA(config = deca_cfg, device=device)
  File "/workspace/raid02/edu/LIHU/lsp/otherlib/deca/decalib/deca.py", line 49, in __init__
    self._create_model(self.cfg.model)
  File "/workspace/raid02/edu/LIHU/lsp/otherlib/deca/decalib/deca.py", line 82, in _create_model
    self.flame = FLAME(model_cfg).to(self.device)
  File "/workspace/raid02/edu/LIHU/lsp/otherlib/deca/decalib/models/FLAME.py", line 77, in __init__
    lmk_embeddings = np.load(config.flame_lmk_embedding_path, allow_pickle=True, encoding='latin1')
  File "/root/lihu/miniconda3/envs/lsp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/raid02/edu/LIHU/lsp/otherlib/deca/data/landmark_embedding.npy'

how can i get this  landmark_embedding.npy file

**Comment by haokunchen0** [comment]
I have the same question, did you solve it?

**Comment by leung-yaya** [comment]
same question，do you  solved it？

**Comment by haokunchen0** [comment]
not yet

leung ***@***.***> 于2023年3月14日周二 19:35写道：

**Comment by xy370283** [comment]
download it from DECA
